export const mockInventory = [
  {
    id: "1",
    name: "T-shirt",
    sku: "M-black",
    quantity: 10,
    price: 1500,
    category: "T-shirt",
    status: "in_stock",
    supplier: "Karpasa",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Pant",
    sku: "L-Jeans",
    quantity: 2,
    price: 2500,
    category: "Pants",
    status: "low_stock",
    supplier: "KarpasaNepal",
    lastUpdated: new Date().toISOString(),
  },
   {
    id: "3",
    name: "Trousers",
    sku: "L-grey",
    quantity: 8,
    price: 1500,
    category: "Trousers",
    status: "in_stock",
    supplier: "KarpasaNepal",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Trousers",
    sku: "L-grey",
    quantity: 8,
    price: 1500,
    category: "Trousers",
    status: "in_stock",
    supplier: "KarpasaNepal",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Pant",
    sku: "L-Jeans",
    quantity: 2,
    price: 2500,
    category: "Pants",
    status: "low_stock",
    supplier: "KarpasaNepal",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "6",
    name: "T-shirt",
    sku: "M-black",
    quantity: 10,
    price: 1500,
    category: "T-shirt",
    status: "in_stock",
    supplier: "Karpasa",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "7",
    name: "T-shirt",
    sku: "M-black",
    quantity: 10,
    price: 1500,
    category: "T-shirt",
    status: "in_stock",
    supplier: "Karpasa",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "8",
    name: "T-shirt",
    sku: "M-black",
    quantity: 10,
    price: 1500,
    category: "T-shirt",
    status: "in_stock",
    supplier: "Karpasa",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "9",
    name: "T-shirt",
    sku: "M-black",
    quantity: 10,
    price: 1500,
    category: "T-shirt",
    status: "in_stock",
    supplier: "Karpasa",
    lastUpdated: new Date().toISOString(),
  }
  

];
